Add an opinionated article about Hacktoberfest
SADevs/sadevs.github.io pull request #53
Opened 2020-10-05 22:13 UTC by cptcrunchy

My personal thoughts about Hacktoberfest and contributing to open source projects

2020-10-05 22:33 UTC, gtmanfred requested changes
Thank you for writing this Jason.

I would love to get this up on the blog, I just have some grammar requests, mostly commas :)

2020-10-05 22:33 UTC, gtmanfred commented on content/articles/2020_10_5_Hacktoberfest_Or_Spamtoberfest?.md
> +
Can you remove these extra newlines?

2020-10-05 22:33 UTC, gtmanfred commented on content/articles/2020_10_5_Hacktoberfest_Or_Spamtoberfest?.md
> +add some text without out much context and that would be considered a valid PR.
`out out`

2020-10-05 22:33 UTC, gtmanfred commented on content/articles/2020_10_5_Hacktoberfest_Or_Spamtoberfest?.md
> +I sympathize with the Youtuber and I believe they had good intentions but I believe
`, but`

2020-10-05 22:33 UTC, gtmanfred commented on content/articles/2020_10_5_Hacktoberfest_Or_Spamtoberfest?.md
> +noble and some projects are only alive because of a community that enjoys the service
`, and`

2020-10-05 22:33 UTC, gtmanfred commented on content/articles/2020_10_5_Hacktoberfest_Or_Spamtoberfest?.md
> +or project but I think there is some underlying barrier that can scare off would be
This has become a run on sentence. Can you reword it?

2020-10-05 22:33 UTC, gtmanfred commented on content/articles/2020_10_5_Hacktoberfest_Or_Spamtoberfest?.md
> +some cases this is necessary, from what I have read and experienced, this is not the case.
Though, in some cases, this is necessary, from what I have read and experienced, that is not the case.

2020-10-05 22:33 UTC, gtmanfred commented on content/articles/2020_10_5_Hacktoberfest_Or_Spamtoberfest?.md
> +shouldn't suffer because of this but rather "inform" would be contributors and follow
Again, another run on sentence.

also, in the middle it is not super clear what "this" is.  Reworking the sentence would be good.

2020-10-05 22:33 UTC, gtmanfred commented on content/articles/2020_10_5_Hacktoberfest_Or_Spamtoberfest?.md
> +prepared and prefaced with a more "beginner" friendly set of instructions they could
instructions, they could

2020-10-05 22:33 UTC, gtmanfred commented on content/articles/2020_10_5_Hacktoberfest_Or_Spamtoberfest?.md
> +If you are looking to contribute to an open source project be mindful of your contribution.
project, be mindful

2020-10-05 22:33 UTC, gtmanfred commented on content/articles/2020_10_5_Hacktoberfest_Or_Spamtoberfest?.md
> +particular chain-link fence. Your contribution may not seem like much but as a city employee
like much, but as a city employee

2020-10-05 22:33 UTC, gtmanfred commented on content/articles/2020_10_5_Hacktoberfest_Or_Spamtoberfest?.md
> +As a contributor, don't be afraid of rules or for that matter contributing. It is an experience that
rules, or for that matter, contributing.

2020-10-05 23:02 UTC, cptcrunchy commented
I made the grammatical corrections. thanks for the review!

2020-10-05 23:11 UTC, andrewthetechie approved these changes
This LGTM, but let's wait to let @gtmanfred review again as well

2020-10-06 13:36 UTC, gtmanfred approved these changes

2020-10-06 13:36 UTC, gtmanfred commented
looks good, thank you for the article @cptcrunchy

2020-10-06 13:36 UTC, merged